name: Build and Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          
      - name: Prepare application.properties
        run: |
          mkdir config
          echo "${{ secrets.YOGIJOGI_APP_PROPERTIES }}" > config/application.properties

      - name: Build with Maven
        run: mvn clean package -DskipTests
          
      - name: Check if jar file exists
        run: |
          echo "Contents of target directory:"
          ls -la target
          if [ ! -f target/yogijogi-0.0.1-SNAPSHOT.jar ]; then
            echo "Error: Jar file not found!"
            exit 1
          fi

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.YOGIJOGI_DOCKER_REPO }} -p ${{ secrets.YOGIJOGI_DOCKER_KEY }}
          docker build -t ${{ secrets.YOGIJOGI_DOCKER_REPO }}/yogijogi-backend:latest .
          docker push ${{ secrets.YOGIJOGI_DOCKER_REPO }}/yogijogi-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YOGIJOGI_HOST }}
          username: ${{ secrets.YOGIJOGI_USERNAME }}
          key: ${{ secrets.YOGIJOGI_SSH_PRIVATE_KEY }}
          script: |
            sudo docker network create yogijogi || true
            sudo docker stop yogijogi-backend || true
            sudo docker rm yogijogi-backend || true
            sudo docker pull ${{ secrets.YOGIJOGI_DOCKER_REPO }}/yogijogi-backend:latest
            sudo docker run -d -p 8080:8080 --net yogijogi --name yogijogi-backend ${{ secrets.YOGIJOGI_DOCKER_REPO }}/yogijogi-backend:latest
